#import <Foundation/Foundation.h>
extern CGFloat const ECLineSpace;
extern CGFloat const ECParagraphSpace;
extern CGFloat const ECBorderSpace;
extern CGFloat const ECContentPageSpace;
extern CGFloat const ECViewSpace;
extern CGFloat const ECNavigationbarHeight;
extern CGFloat const ECViewBackgroundAlpha;
extern NSInteger const ECTextViewMaxInput;
extern NSInteger const ECLineTag;
@interface HWStyle : NSObject
+ (CGFloat)screenWidth;
+ (CGFloat)screenHeight;
+ (CGFloat)statusbarHeight;
+ (CGFloat)navigationbarHeight;
+ (CGFloat)toolbarHeight;
+ (CGFloat)tabbarExtensionHeight;
+ (CGFloat)activityIndicatorSize;
+ (CGFloat)loadingOffsetYInListView;
+ (CGFloat)emptyOffsetYInListView;
+ (CGFloat)failOffsetYInListView;
+ (CGFloat)separatorLineHeight;
+ (CGFloat)separatorLeftMargin;
+ (CGFloat)buttonCornerRadius;
+ (CGFloat)buttonBorderWidth;
+ (CGFloat)viewPagerCursorHeight;
+ (CGFloat)viewPagerHeight;
+ (CGRect)fullScrTableFrame:(BOOL)inTab;
+ (CGRect)viewPagerFrame;
+ (CGRect)viewReminderFrame;
+ (UIColor *)redThemeColor;
+ (UIColor *)greenThemeColor;
+ (UIColor *)blackTextColor;
+ (UIColor *)darkGrayTextColor;
+ (UIColor *)grayTextColor;
+ (UIColor *)lightGrayTextColor;
+ (UIColor *)whiteTextColor;
+ (UIColor *)grayLineColor;
+ (UIColor *)darkGrayLineColor;
+ (UIColor *)backGroundColor;
+ (UIColor *)lightBackGroundColor;
+ (UIColor *)color1;
+ (UIColor *)color2;
+ (UIColor *)color3;
+ (UIColor *)color4;
+ (UIFont *)normalFont;
+ (UIFont *)smallerFont;
+ (UIFont *)largerFont;
+ (UIFont *)larger2Font;
+ (UIFont *)largerBoldFont;
+ (UIFont *)larger2BoldFont;
+ (CGFloat)normalFontHeight;
+ (CGFloat)largeFontHeight;
+ (CGFloat)large2FontHeight;
+ (CGFloat)smallFontHeight;
+ (CGFloat)largeBoldFontHeight;
+ (CGFloat)large2BoldFontHeight;
@end
